---
apiVersion: v1
kind: Service
metadata:
  name: shinka
  labels:
    app.kubernetes.io/name: shinka
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
  selector:
    app.kubernetes.io/name: shinka
    app.kubernetes.io/component: operator
