---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shinka
  labels:
    app.kubernetes.io/name: shinka
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shinka
subjects:
  - kind: ServiceAccount
    name: shinka
    namespace: shinka-system
